config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  # resources :users, only: [:create, :new]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users' => 'users#index'

  get '/add_piano' => 'pianos#new'

  resources :detail_pictures

  resources :pianos do
    resources :photos
  end

  resources :posts do
    resources :comments
  end


  get '/blog' => 'site#blog'

  root to: 'site#index'
  # resources :pictures, only: [:new, :create, :index]
  # root to: 'pictures#index'

  namespace :api do
    namespace :v1 do
      resources :pictures
      # resources :pianos, only: [:index, :create, :destroy, :update, :find_photos]

    end
  end
  get 'pianos/:id/find_photo', :to => 'pianos#find_photos'


  get 'detail_pictures/photo_url', :to => 'detail_pictures#photo_url'

end

app/models/detail_picture.rb
class DetailPicture < ApplicationRecord
  dragonfly_accessor :image
end

app/controllers/detail_pictures_controller.rb
class DetailPicturesController < ApplicationController
  before_action :set_detail_picture, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /detail_pictures
  # GET /detail_pictures.json
  def index
    @pic_images = []
    @detail_pictures = DetailPicture.all
    @detail_pictures.map { |picture| @pic_images << picture.image.url }
    respond_with @detail_pictures do |format|
      format.json {render :json => @pic_images, :layout => false }
    end
  end

  # GET /detail_pictures/1
  # GET /detail_pictures/1.json
  def show
  end

  # GET /detail_pictures/new
  def new
    @detail_picture = DetailPicture.new
  end

  # GET /detail_pictures/1/edit
  def edit
  end

  # POST /detail_pictures
  # POST /detail_pictures.json
  def create
    @detail_picture = DetailPicture.new(detail_picture_params)

    respond_to do |format|
      if @detail_picture.save
        format.html { redirect_to @detail_picture, notice: 'Detail picture was successfully created.' }
        format.json { render :show, status: :created, location: @detail_picture }
      else
        format.html { render :new }
        format.json { render json: @detail_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detail_pictures/1
  # PATCH/PUT /detail_pictures/1.json
  def update
    respond_to do |format|
      if @detail_picture.update(detail_picture_params)
        format.html { redirect_to @detail_picture, notice: 'Detail picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail_picture }
      else
        format.html { render :edit }
        format.json { render json: @detail_picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detail_pictures/1
  # DELETE /detail_pictures/1.json
  def destroy
    @detail_picture.destroy
    respond_to do |format|
      format.html { redirect_to detail_pictures_url, notice: 'Detail picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail_picture
      @detail_picture = DetailPicture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def detail_picture_params
      params.require(:detail_picture).permit(:image, :title)
    end
end

app/helpers/detail_pictures_helper.rb
module DetailPicturesHelper
end

app/views/detail_pictures/_form.html.erb
<%= form_for(detail_picture) do |f| %>
  <% if detail_picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(detail_picture.errors.count, "error") %> prohibited this detail_picture from being saved:</h2>

      <ul>
      <% detail_picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, required: true %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/detail_pictures/edit.html.erb
<h1>Editing Detail Picture</h1>

<%= render 'form', detail_picture: @detail_picture %>

<%= link_to 'Show', @detail_picture %> |
<%= link_to 'Back', detail_pictures_path %>

app/views/detail_pictures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Detail Pictures</h1>

<table>
  <thead>
    <tr>
      <th>Image uid</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @detail_pictures.each do |detail_picture| %>
      <tr>
        <img src='<%= detail_picture.image.thumb('200x200#').url %>' />
        <td><%= detail_picture.image.url %></td>
        <td><%= detail_picture.title %></td>
        <td><%= link_to 'Show', detail_picture %></td>
        <td><%= link_to 'Edit', edit_detail_picture_path(detail_picture) %></td>
        <td><%= link_to 'Destroy', detail_picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Detail Picture', new_detail_picture_path %>

app/views/detail_pictures/new.html.erb
<h1>New Detail Picture</h1>

<%= render 'form', detail_picture: @detail_picture %>

<%= link_to 'Back', detail_pictures_path %>

app/views/detail_pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image uid:</strong>
  <%= @detail_picture.image_uid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @detail_picture.title %>
</p>

<%= link_to 'Edit', edit_detail_picture_path(@detail_picture) %> |
<%= link_to 'Back', detail_pictures_path %>